kom/update-readme-file Fix wrong readme repo names
flarum/flarum pull request #79
Opened 2021-12-16 20:49 UTC by komandar

Fix wrong repository names in readme file and removed travis.

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2021-12-16 21:21 UTC, davwheat requested changes
These should still be links to flarum/core, as that's our main code repo. flarum/flarum is purely a project template and Flarum can be used without it.

2021-12-16 21:29 UTC, komandar commented
> These should still be links to flarum/core, as that's our main code repo. flarum/flarum is purely a project template and Flarum can be used without it.

Sure I understand that. But when you see the badges in a repository you expect it to be the data from the actively selected repository and not from another one (even if it is the central one in that case).

2021-12-17 18:59 UTC, SychO9 commented
Thanks for the PR!

@davwheat 's correct 👼🏼 the badges should point to the core repository, this is only a skeleton and we'd rather have data from the main framework.

2021-12-17 19:15 UTC, tankerkiller125 commented
Given the previous stated reasons and information provided I'm going to go ahead and close this PR.

We do thank you for your eagerness to help and interest in Flarum, to find all the ways you can help please read https://docs.flarum.org/#help-the-flarum-project

2021-12-17 19:15 UTC, closed without merging